package ocm.cookinglegend.domain;

import java.util.Date;

public class PlayerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.id
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.name
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.image
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.level
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.experience
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.tasks
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String tasks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.feats
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String feats;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.coins
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer coins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.golds
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer golds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.platform
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.device
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.genueId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer genueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.energy
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer energy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.server
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer server;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.nickname
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.gangId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer gangId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.registered
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Date registered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.deleted
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.reservedInt1
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer reservedInt1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.groupId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.password
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Players.email
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.id
     *
     * @return the value of Players.id
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.id
     *
     * @param id the value for Players.id
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.name
     *
     * @return the value of Players.name
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.name
     *
     * @param name the value for Players.name
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.image
     *
     * @return the value of Players.image
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.image
     *
     * @param image the value for Players.image
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.level
     *
     * @return the value of Players.level
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.level
     *
     * @param level the value for Players.level
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.experience
     *
     * @return the value of Players.experience
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.experience
     *
     * @param experience the value for Players.experience
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.tasks
     *
     * @return the value of Players.tasks
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getTasks() {
        return tasks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.tasks
     *
     * @param tasks the value for Players.tasks
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setTasks(String tasks) {
        this.tasks = tasks == null ? null : tasks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.feats
     *
     * @return the value of Players.feats
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getFeats() {
        return feats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.feats
     *
     * @param feats the value for Players.feats
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setFeats(String feats) {
        this.feats = feats == null ? null : feats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.coins
     *
     * @return the value of Players.coins
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getCoins() {
        return coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.coins
     *
     * @param coins the value for Players.coins
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setCoins(Integer coins) {
        this.coins = coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.golds
     *
     * @return the value of Players.golds
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getGolds() {
        return golds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.golds
     *
     * @param golds the value for Players.golds
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setGolds(Integer golds) {
        this.golds = golds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.platform
     *
     * @return the value of Players.platform
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.platform
     *
     * @param platform the value for Players.platform
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.device
     *
     * @return the value of Players.device
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.device
     *
     * @param device the value for Players.device
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.genueId
     *
     * @return the value of Players.genueId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getGenueId() {
        return genueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.genueId
     *
     * @param genueId the value for Players.genueId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setGenueId(Integer genueId) {
        this.genueId = genueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.energy
     *
     * @return the value of Players.energy
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.energy
     *
     * @param energy the value for Players.energy
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setEnergy(Integer energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.server
     *
     * @return the value of Players.server
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.server
     *
     * @param server the value for Players.server
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setServer(Integer server) {
        this.server = server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.nickname
     *
     * @return the value of Players.nickname
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.nickname
     *
     * @param nickname the value for Players.nickname
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.gangId
     *
     * @return the value of Players.gangId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getGangId() {
        return gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.gangId
     *
     * @param gangId the value for Players.gangId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setGangId(Integer gangId) {
        this.gangId = gangId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.registered
     *
     * @return the value of Players.registered
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Date getRegistered() {
        return registered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.registered
     *
     * @param registered the value for Players.registered
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setRegistered(Date registered) {
        this.registered = registered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.deleted
     *
     * @return the value of Players.deleted
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.deleted
     *
     * @param deleted the value for Players.deleted
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.reservedInt1
     *
     * @return the value of Players.reservedInt1
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getReservedInt1() {
        return reservedInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.reservedInt1
     *
     * @param reservedInt1 the value for Players.reservedInt1
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setReservedInt1(Integer reservedInt1) {
        this.reservedInt1 = reservedInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.groupId
     *
     * @return the value of Players.groupId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.groupId
     *
     * @param groupId the value for Players.groupId
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.password
     *
     * @return the value of Players.password
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.password
     *
     * @param password the value for Players.password
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Players.email
     *
     * @return the value of Players.email
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Players.email
     *
     * @param email the value for Players.email
     *
     * @mbggenerated Sat Jan 19 15:46:15 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}