package ocm.cookinglegend.dao;

import java.util.List;
import ocm.cookinglegend.domain.PlayerInfo;
import ocm.cookinglegend.domain.PlayerInfoExample;
import org.apache.ibatis.annotations.Param;

public interface PlayerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int countByExample(PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int deleteByExample(PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int insert(PlayerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int insertSelective(PlayerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    List<PlayerInfo> selectByExample(PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    PlayerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int updateByExampleSelective(@Param("record") PlayerInfo record, @Param("example") PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int updateByExample(@Param("record") PlayerInfo record, @Param("example") PlayerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int updateByPrimaryKeySelective(PlayerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Players
     *
     * @mbggenerated Sat Jan 19 17:01:02 CST 2013
     */
    int updateByPrimaryKey(PlayerInfo record);
}